### ISSUE TITLE
Tab Stats icon disappears when Verticle Tabs is enabled

### ISSUE THREAD

**Issue by pmac** [glandium/tabstats#16]
This is an experimental "Firefox Labs" feature in Nightly right now, but I thought it'd be nice to let you know early in case the feature does fully land. Probably not much that can be done at this point. Thanks for a fantastic addon!

**Comment by glandium** [comment]
That sounds like a bug in Firefox's vertical tabs. The addon does nothing special here, it's only using WebExtensions's browser_action, with default_area set to tabstrip. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action

**Comment by pmac** [comment]
That seems likely. Should I file something in bugzilla you think?

**Comment by glandium** [comment]
Maybe ask if it's a known issue first?

**Comment by pmac** [comment]
I'm told in the slack channel that there are no plans to make the verticle tabstrip customizable and so I guess addons will just be broken. Not much we can do about it. I'll just not use verticle tabs. Easy fix.
