### ISSUE TITLE
Number of groups is inaccurate if you haven't opened Panorama since your last restart

### ISSUE THREAD

**Issue by justdave** [glandium/tabstats#2]
The summary at the top listing the number of tab groups exactly matches the number of windows if you run tabstats immediately after a restart + session restore.  In order to get it to update with the correct number of tab groups, you must go through each window and open Panorama in each of them.

**Comment by glandium** [comment]
Yeah, that's due to how panorama works. If you have an idea how to get that right, I'm all ears. I failed to find one, but I don't think I've looked very deeply.

**Comment by justdave** [comment]
I suspected as much.  I've never touched most of the code behind the browser before so I wouldn't even know where to look.

**Comment by glandium** [comment]
Fixed by 2209e5f
