### ISSUE TITLE
Not compatible with Firefox 57

### ISSUE THREAD

**Issue by justdave** [glandium/tabstats#7]
This extension is tagged as "Legacy" in the Addons Manager, which means it will cease functioning in Firefox 57.  Any plans to update it to a WebExtension?

**Comment by glandium** [comment]
I've been meaning to rewrite it as a webextension, from scratch. I haven't found the time to just yet. Maybe I should first try a conversion of the current code base if that's possible. I'm not sure webextensions can trigger chrome actions from content... also, webextensions, about: urls can't be registered, so there would also need to be a change there...

**Comment by justdave** [comment]
could always put a button in the menu that opens a chrome: url or something.

**Comment by glandium** [comment]
I did a basic conversion, and it mostly works. I had to remove favicons, though, because I can't add xul:image tags, which are necessary to get the favicons without hitting the network (with validate=never)

**Comment by justdave** [comment]
Looks awesome. :-)
